# Generated by Django 6.0.3 on 2026-03-17 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('short_name', models.CharField(max_length=10, verbose_name='Сокращение')),
                ('plural_name', models.CharField(blank=True, max_length=50, verbose_name='Множественное число')),
                ('ratio_to_base', models.DecimalField(decimal_places=6, default=1, help_text='Например: для грамма = 0.001 (кг базовая), для тонны = 1000', max_digits=12, verbose_name='Коэффициент к базовой')),
                ('is_base', models.BooleanField(default=False, help_text='Базовая единица, к которой приводятся остальные', verbose_name='Базовая в группе')),
                ('is_default', models.BooleanField(default=False, help_text='Использовать по умолчанию для новых товаров', verbose_name='По умолчанию')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название группы')),
                ('slug', models.SlugField(unique=True, verbose_name='Идентификатор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='📏', max_length=10, verbose_name='Иконка (emoji)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Группа единиц',
                'verbose_name_plural': 'Группы единиц',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='categories/icons/', verbose_name='Иконка'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Родительская категория'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Сортировка'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL-идентификатор'),
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Добавил'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('slug', 'parent')},
        ),
        migrations.CreateModel(
            name='ProductField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Идентификатор')),
                ('field_type', models.CharField(choices=[('text', 'Текст (однострочный)'), ('textarea', 'Текст (многострочный)'), ('number', 'Число'), ('decimal', 'Десятичное число'), ('boolean', 'Да/Нет (checkbox)'), ('select', 'Выбор из списка'), ('multiselect', 'Множественный выбор'), ('date', 'Дата'), ('datetime', 'Дата и время'), ('image', 'Изображение'), ('file', 'Файл'), ('url', 'Ссылка'), ('email', 'Email'), ('phone', 'Телефон'), ('color', 'Цвет'), ('range', 'Диапазон')], max_length=20, verbose_name='Тип поля')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='Подсказка')),
                ('options', models.JSONField(blank=True, default=dict, help_text='{"choices": ["A", "B"], "min": 0, "max": 100}', verbose_name='Параметры')),
                ('default_value', models.JSONField(blank=True, null=True, verbose_name='Значение по умолчанию')),
                ('required', models.BooleanField(default=False, verbose_name='Обязательное')),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Минимум')),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Максимум')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мин. длина')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='Макс. длина')),
                ('pattern', models.CharField(blank=True, max_length=500, verbose_name='Регулярное выражение')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('is_filterable', models.BooleanField(default=False, verbose_name='Использовать в фильтре')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Показывать в карточке')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='Единица измерения')),
                ('categories', models.ManyToManyField(related_name='fields', to='products.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Поле товара',
                'verbose_name_plural': 'Поля товаров',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.unit', verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='unit',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='products.unitgroup', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='category',
            name='allowed_unit_groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_categories', to='products.unitgroup', verbose_name='Разрешённые группы единиц'),
        ),
        migrations.CreateModel(
            name='ProductFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(verbose_name='Значение')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.productfield')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='products.product')),
            ],
            options={
                'verbose_name': 'Значение поля',
                'verbose_name_plural': 'Значения полей',
                'unique_together': {('product', 'field')},
            },
        ),
        migrations.CreateModel(
            name='CategoryUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='По умолчанию')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Сортировка')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_units', to='products.category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_categories', to='products.unit')),
            ],
            options={
                'verbose_name': 'Допустимая единица для категории',
                'verbose_name_plural': 'Допустимые единицы для категорий',
                'ordering': ['sort_order', 'unit__name'],
                'unique_together': {('category', 'unit')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('group', 'short_name')},
        ),
    ]
