# Generated by Django 6.0.3 on 2026-03-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий админа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Запрос на добавление категории',
                'verbose_name_plural': 'Запросы на добавление категорий',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('unit', models.CharField(choices=[('шт', 'Штук'), ('кг', 'Килограмм'), ('л', 'Литр'), ('м', 'Метр'), ('упак', 'Упаковка')], default='шт', max_length=10, verbose_name='Единица измерения')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('has_discount', models.BooleanField(default=False, verbose_name='Есть скидка')),
                ('discount_percent', models.PositiveSmallIntegerField(default=0, verbose_name='Процент скидки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='requests/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=10, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий админа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Запрос на добавление товара',
                'verbose_name_plural': 'Запросы на добавление товаров',
                'ordering': ['-created_at'],
            },
        ),
    ]
