# Generated by Django 6.0.3 on 2026-03-17 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryRequest',
        ),
    ]
