# Generated by Django 6.0.3 on 2026-03-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Токен авторизации'),
        ),
    ]
