name: Deploy to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "backend/,frontend/,docker-compose.yml,frontend/Dockerfile,frontend/nginx.conf,backend/Dockerfile"
          target: "/root/docker-project"
          strip_components: 0
          overwrite: true

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /root/docker-project
            # Копируем сертификаты если есть
            mkdir -p frontend/ssl
            cp /etc/letsencrypt/live/csmevg.ru/fullchain.pem frontend/ssl/ 2>/dev/null || echo "Сертификаты не найдены"
            cp /etc/letsencrypt/live/csmevg.ru/privkey.pem frontend/ssl/ 2>/dev/null || echo "Сертификаты не найдены"
            
            # Перезапускаем
            docker compose down
            docker compose up -d --build
